handleParsedAddressLoadError: element argument
Allow handleParsedAddressLoadError to report error using specified HTMLElement rather than being tied to Inspector.linkDivFirstPara. This is required for suggested matches, where error will be reported in suggested match div.